import { ReduxProvider } from "@/store/ReduxProvider";
import Layout from "@/componets/layout/Layout";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sahal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-hidden">
      <body suppressHydrationWarning={true}>
        <ReduxProvider>
          <Layout>{children}</Layout>
        </ReduxProvider>
      </body>
    </html>
  );
}
