export const endpoints = {
  store: "store",
  order: "order",
  brand: "brand",
  login: "auth/login",
  products: "product",
  customer: "customer",
  category: "category",
  register: "auth/register",
  allCategory: "category/all",
  searchProduct: "product/search",
  newPassword: "auth/new-password",
  verification: "auth/verification",
  categoryProduct: "category/product",
  searchBrand: "brand/search-category",
  forgetPassword: "auth/forget-password",
  searchCategory: "category/search-category",
  verifyForgetPassword: "auth/forget-password-verify",
};
